wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1667631876.929474
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 23
      - 32
      4: 3.10.8
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
